num_classes = 103
num_epochs = 200
batch_size = 128
patience = 36
learning_rate = 0.001
decay = 0.9
feature_shape = [None, 8, 8, 1536]
image_size = 299
inception_resnet_model = './model_inc/inc_res.ckpt'
resnet_model = './model/resnet.ckpt'
new_data_resnet = 'new_data.pickle'
new_data_inception = 'new_data_inc.pickle'
